- name: OCP PREREQ
  hosts: all
  become: true
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present
    - name: Run docker-storage-setup
      shell: docker-storage-setup
