- name: OCP PREREQ
  hosts: all
  become: true
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present
      when: docker
    - name: Run docker-storage-setup
      shell: docker-storage-setup
      when: docker
    - name: Configure Chronyd
      copy:
        src: chrony.conf
        dest: /etc/chrony.conf
    - name: restart Chrony
      service:
        name: chronyd
        state: restarted

